name: Test and Publish
on: ["push", "pull_request"]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Test and generate coverage
        run: |
          npm ci
          npm run test:prod

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Commit docs
        run: |
          cd docs
          touch .nojekyll
          git init
          git add .
          git config user.name "glebbash"
          git config user.email "glebbash@gmail.com"
          git commit -m "docs(docs): update gh-pages"

      - name: Publish docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: docs
          branch: master:gh-pages
          force: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
